### ISSUE TITLE
EventMeta table is nil in 2.5.6

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1273]
Breaks things like SpawnAtAirbase(), causes log spam, broken A2A_Dispatcher, RAT

Can be reproduced with a simple SpawnAtAirbase() like like
```
Spawn_Plane = SPAWN:New( "Plane" )
Spawn_Plane:SpawnAtAirbase( AIRBASE:FindByName( AIRBASE.Caucasus.Krymsk ), SPAWN.Takeoff.Cold )
```
```


2020-02-15 22:22:09.412 INFO    SCRIPTING:  39719( 26554)/E:                       AIRBASE00055.FindFreeParkingSpotForAircraft(Krymsk: Looking for 1 parking spot(s) for aircraft of size 18.9 m (x=16.8,y=3.7,z=18.9) at termial type 244.)
2020-02-15 22:22:09.412 INFO    SCRIPTING:  39824( 26554)/I:                       AIRBASE00055.FindFreeParkingSpotForAircraft(Krymsk: Parking spot id 58 free.)
2020-02-15 22:22:09.412 INFO    SCRIPTING:  39829( 26554)/I:                       AIRBASE00055.FindFreeParkingSpotForAircraft(Krymsk: Parking spot id 58 free. Nfree=1/1.)
2020-02-15 22:22:09.423 ERROR   DCS: Mission script error: : [string "C:\Users\thebg\AppData\Local\Temp\DCS.openbeta\/~mis0000215D.lua"]:7076: attempt to index local 'EventMeta' (a nil value)
stack traceback:
    [C]: ?
    [string "C:\Users\thebg\AppData\Local\Temp\DCS.openbeta\/~mis0000215D.lua"]:7076: in function 'onEvent'
    [string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```
Not sure where to start but this is critical for 2.5.6. The event id's all changed

**Comment by thebgpikester** [comment]
Fixed with franks new pull but realistically was Wingthor that did the same earlier.

**Comment by ozdeadmeat** [comment]
I am running the build from the 5th of April (Latest commit 412fc3d) and I can confirm that the Event bug is still present.

**Comment by pabclsn** [comment]
Same here with develop branch ...
