### ISSUE TITLE
AUFTRAG:NewESCORT() - Strange Behavior

### ISSUE THREAD

**Issue by Carlton2001** [FlightControl-Master/MOOSE#1368]
Hi,

I don't understand the behavior of NewESCORT() since the last MOOSE build.
At the first evaluation of this Auftrag, it stops ; Final Success = true because the target is alive.
Yes hopefully it's alive :), the Auftrag shouldn't end for this. In my opinion, by default, the escort should remain active until the target is landed or dead. It was working before.
(In addition, Escort's target must exists before the Escort's birth)

**Exemple**
```lua
local MissionTankerRed = AUFTRAG:NewTANKER(ZONE:New("Zone_Tanker_Red"):GetCoordinate(), 20000, 350)
local TankerRed = FLIGHTGROUP:New("Tanker_Red")
TankerRed:AddMission(MissionTankerRed)
function TankerRed:onafterSpawned (From, Event, To)
	local MissionEscortTankerRed = AUFTRAG:NewESCORT(TankerRed:GetGroup())
	local EscortTankerRed = FLIGHTGROUP:New("Escort_Red")
	EscortTankerRed:AddMission(MissionEscortTankerRed)
end
```

**1st Evaluation**
```
2020-11-16 05:16:47.106 INFO SCRIPTING: 117772(117667)/I: AUFTRAG01074.Evaluate(Auftrag #2 Escort | Evaluating mission:
Own casualties = 0/1
Own losses     = 0.0 
Killed units   = 0
--------------------------
Targets left   = 1/1
Targets life   = 60.0/60.0
Enemy losses   = 0.0 
--------------------------
Success Cond   = false
Failure Cond   = false
--------------------------
Final Success  = true
=========================)
2020-11-16 05:16:47.106 INFO SCRIPTING: 118227(    -1)/I: AUFTRAG01074.function(Auftrag #2 Escort | Mission SUCCESS! Number of max repeats 1 reached  ==> Stopping mission!)
2020-11-16 05:16:47.106 INFO SCRIPTING: 118336(    -1)/I: AUFTRAG01074.function(Auftrag #2 Escort | STOPPED mission in status=success. Removing missions from queues. Stopping CallScheduler!)
```

**Comment by funkyfranky** [comment]
Thanks for the report! The bug that you need to wait until the escorted group is alive is now fixed (always use OnAfterSpawned with capitals, btw. If you use lower case, you overwrite internal functions.)

The rest is working as intended. The AUFTRAG is evaluated when the DCS task ends. That seems to not to include to wait until the escorted group landed.

**Comment by Carlton2001** [comment]
Thanks for the reply Franky.

But I don't understand. If I use OnAfterSpawned (very last MOOSE build) I still have the same problem, the escort mission immediatly succeeded and the escort plane goes RTB.

```lua
local MissionTankerRed = AUFTRAG:NewTANKER(ZONE:New("Zone_Tanker_Red"):GetCoordinate(), 20000, 350)
local TankerRed = FLIGHTGROUP:New("Tanker_Red")
TankerRed:AddMission(MissionTankerRed)
function TankerRed:OnAfterSpawned (From, Event, To)
	local MissionEscortTankerRed = AUFTRAG:NewESCORT(TankerRed:GetGroup())
	local EscortTankerRed = FLIGHTGROUP:New("Escort_Red")
	EscortTankerRed:AddMission(MissionEscortTankerRed)
end
```

If I don't use OnAfterSpawned, the escort never spawn and the escort mission is cancelled

```lua
local MissionTankerRed = AUFTRAG:NewTANKER(ZONE:New("Zone_Tanker_Red"):GetCoordinate(), 20000, 350)
local TankerRed = FLIGHTGROUP:New("Tanker_Red")
TankerRed:AddMission(MissionTankerRed)
local MissionEscortTankerRed = AUFTRAG:NewESCORT(TankerRed:GetGroup())
local EscortTankerRed = FLIGHTGROUP:New("Escort_Red")
EscortTankerRed:AddMission(MissionEscortTankerRed)
```

If I activate the escort plane immediatly (so it spawn before the tanker), the escort mission is cancelled.

```lua
local MissionTankerRed = AUFTRAG:NewTANKER(ZONE:New("Zone_Tanker_Red"):GetCoordinate(), 20000, 350)
local TankerRed = FLIGHTGROUP:New("Tanker_Red")
TankerRed:AddMission(MissionTankerRed)
local MissionEscortTankerRed = AUFTRAG:NewESCORT(TankerRed:GetGroup())
local EscortTankerRed = FLIGHTGROUP:New("Escort_Red"):Activate()
EscortTankerRed:AddMission(MissionEscortTankerRed)
```

If I spawn both plane at the same time, I have the same result as case 1, mission success immediatly, escort plane goes RTB.

```lua
local MissionTankerRed = AUFTRAG:NewTANKER(ZONE:New("Zone_Tanker_Red"):GetCoordinate(), 20000, 350)
local TankerRed = FLIGHTGROUP:New("Tanker_Red"):Activate()
TankerRed:AddMission(MissionTankerRed)
local MissionEscortTankerRed = AUFTRAG:NewESCORT(TankerRed:GetGroup())
local EscortTankerRed = FLIGHTGROUP:New("Escort_Red"):Activate()
EscortTankerRed:AddMission(MissionEscortTankerRed)
```

**Comment by Carlton2001** [comment]
Thank you very much Franky, Escort is working again with your last build,
Should I close the report ?

**Comment by funkyfranky** [comment]
Thanks for the feedback!
