### ISSUE TITLE
DESIGNATE: Laser not working after: Auto On-> Auto Off -> Stop Lasing

### ISSUE THREAD

**Issue by dslawek** [FlightControl-Master/MOOSE#750]
If choose 'Auto Lase On', then 'Auto Lase Off', then 'Stop Lasing', Laser never will work again.

DCS: 1.5.7.11762
Moose Generation Timestamp: 20171031_1115

**Comment by FlightControl-Master** [comment]
@dslawek ok, i will check this

**Comment by FlightControl-Master** [comment]
This issue is fixed. Please download the latest release 2.3-alpha moose.lua from the release page.

**Comment by dslawek** [comment]
Unfortunately, 'Auto Lase On' > 'Auto Lase Off' > 'Stop lasing' > 'Auto Lase On' still does not work.
https://youtu.be/0jXH9y52u4g

DCS: 1.5.8.12667
Moose: 20171218_1151

**Comment by FlightControl-Master** [comment]
ha! sorry. it is another issue. this is not about designate not lasing, but being unable to stop. Sorry. yup. confirmed.

**Comment by FlightControl-User** [comment]
Note there is a new version of designate. This issue has been fixed.  Pls test.

**Comment by dslawek** [comment]
Now it is working. Thanks!

But I see another problem. With time, too much messages about lasing:
start: https://youtu.be/ER43dcWkKEo
after ~10min: https://youtu.be/VDrK5bzh4u4

**Comment by Delta-99** [comment]
@FlightControl-User can we close this one? Is the last comment actually a new issue that we can open if needed? Otherwise lets close this one.

**Comment by FlightControl-User** [comment]
worked heavily on designate. this is fixed.
