### ISSUE TITLE
[TASKING] changes from BAI - CAS - BAI when Client aircraft go in and out of range.

### ISSUE THREAD

**Issue by JGrinnelli** [FlightControl-Master/MOOSE#772]
[TASKING] changes from BAI - CAS - BAI when Client aircraft go in and out of range.

I only saw this happen with planes when they were either on a bomb run and got way too close or just orbiting the target area too close would cause the task to change. Basic scripting was used for the tasking.~JG

```lua
local Mission = MISSION
  :New( HQ, "Air-Ground Training","Practice","Practice Air-Ground weapon employment in a controlled enviroment.n/".. 
  "The target area will be marked by green smoke. Designate is available for target lase.n/".. 
  "Do not forget to join a task!", coalition.side.BLUE )
  :AddScoring( Score )
    
local RecceSet = SET_GROUP:New():FilterCoalitions("blue"):FilterPrefixes( "JTAC" ):FilterStart()

local DetectionAreas = DETECTION_AREAS:New( RecceSet, 5000 )
--M1_DetectionAreas:BoundDetectedZones()
  
local Mission1_Attack = SET_GROUP:New():FilterCoalitions( "blue" ):FilterPrefixes( "6thVFW" ):FilterStart()
  
--Mission Task
Mission_TaskA2GDispatcher = TASK_A2G_DISPATCHER:New( Mission, Mission1_Attack, DetectionAreas )

Mission_Designate = DESIGNATE:New( HQ, DetectionAreas, Mission1_Attack, Mission )

Mission_Designate:SetThreatLevelPrioritization( true )

Mission_Designate:GenerateLaserCodes()

Mission_Designate:AddMenuLaserCode( 1111, "Lase with %d for AV-8B" )
Mission_Designate:AddMenuLaserCode( 1113, "Lase with %d for Su-25T" )
Mission_Designate:AddMenuLaserCode( 1688, "Lase with %d for A-10C & Others" )```

**Comment by FlightControl-Master** [comment]
OK. I will try to resimulate and fix the issue.

**Comment by FlightControl-Master** [comment]
This issue is fixed now.
I have approached the fix in an intellegent way. I added an extra Friendlies detection filter method, that will only decide friendlies are nearby if they are of a specific category (in A2G this would be GROUND).
So the detection won't report a friendly airplane near the target as friendly anymore!

**Comment by victorcotap** [comment]
In the latest moose I can still reproduce that issue.
Groups of enemy targets on the ground, by themselves -> Task dispatcher creates a BAI task.
Fly to and within the zone -> Task cancelled and CAS task created
Fly out and it reverts back to BAI

It's live and testable on TTI 2.2

**Comment by FlightControl-User** [comment]
@victorcotap i will check this again.

**Comment by FlightControl-User** [comment]
@victorcotap @JGrinnelli What Moose.lua version were you testing this with?

Release 2.2? Release 2.3-alpha or the latest Moose.lua on MOOSE_INCLUDE?

**Comment by FlightControl-User** [comment]
Also @victorcotap and @JGrinnelli it is normal that a BAI task is converted to a CAS.
A BAI task won't be converted to a CAS task when it is assigned.
I have made test mission TAD-107 which models this scenario.

**Comment by FlightControl-User** [comment]
I've been looking at the code and think i can heavily optimize and make it more clear how friendlies are interpreted. I will rework some of the code.

**Comment by victorcotap** [comment]
I'm always using TOT master, I usually update every 2 days.
The moose include file had remained the same since you helped me set it up months ago, that's why when I switch to the new one after the big reorganization a few weeks ago, it messed it up.
@FlightControl-User I understand a BAI task can be converted to CAS, I just think in this case there was no blue ground units around when it did. It's not 100% reproducible like I detailed on Discord

**Comment by FlightControl-User** [comment]
Well, I've reviewed my code and just did a new push of a change that i think will fix this forever. Can you guys test the change? The new code is pushed on master and a new moose.lua can be downloaded from MOOSE_INCLUDE. thanks @victorcotap and @JGrinnelli etc for alterting on this one.

**Comment by FlightControl-User** [comment]
closing. This is fixed.
