### ISSUE TITLE
MOOSE interference with sl mods

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#83]
3 tries of setting up a clean dcs world environment including sl mods running a moose scripted mission ran into the following failures.

1.
[string "C:\Users\DCS-SE~1\AppData\Local\Temp\DCS.openalpha\/~mis0000324E"]:7: attempt to index global 'debug' (a nil value)

2.
[string "C:\Users\DCS-SE~1\AppData\Local\Temp\DCS.openalpha\/~mis0000324E"]:12: attempt to index field 'Files' (a nil value)

As sl mod is a widely used mod for hosters, it would be great to resolve this issue.

**Comment by FlightControl-Master** [comment]
Am investigating it right now ..

**Comment by FlightControl-Master** [comment]
Done a fix for SLMOD, through pull request #93. Can you please retest?

**Comment by CraigOwen** [comment]
The test was not successful. The logfile still shows both erros mentioned above.

**Comment by FlightControl-Master** [comment]
Are you sure you are using the latest Moose.lua file in your mission? Please send me the DCS.log file.

**Comment by FlightControl-Master** [comment]
Is this still the case?

**Comment by FlightControl-Master** [comment]
@CraigOwen can you confirm?

**Comment by FlightControl-Master** [comment]
Moving this to moose future. It has to do with the lua debug variable conflict. Cannot be resolved in release 2.0.
@CraigOwen can you confirm?

**Comment by CraigOwen** [comment]
Tested this in many many cases. This one is definetly resolved and can therefore be closed.
